/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odoo.client;

import odoo.client.service.OdooService;
import org.apache.xmlrpc.XmlRpcException;

import java.net.MalformedURLException;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws MalformedURLException, XmlRpcException {
        OdooService service = new OdooService();

        service.login();
        final String modelName = "survey.user_input";
        List<Object> params = Arrays.asList(Arrays.asList("active", "=", true));

        List<Integer> ids = service.search(modelName, Collections.emptyList(), new HashMap() {{
            put("limit", 1);
        }});


//        Map<Object, Object> surveyFields = new HashMap() {{
//            put("fields", Arrays.asList("survey_type", "questions_layout", "questions_selection", "access_mode", "scoring_type", "title", "description", "create_uid"));
//        }};

        List<Object> surveys = service.read(modelName, ids);

        System.out.println(surveys);


        Object user = service.create("res.users", new HashMap() {
            {
                put("login", "phone");

            }
        });

        System.out.println(user);


    }
}
